# Generated by Django 3.2.6 on 2021-09-11 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_documento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da Recomendação')),
                ('dat_ini', models.DateField(blank=True, null=True, verbose_name='Data de Inicio')),
                ('dat_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('dat_prevista', models.DateField(blank=True, null=True, verbose_name='Previsão')),
                ('dat_prorrogacao', models.DateField(blank=True, null=True, verbose_name='Data de Prorrogação')),
                ('qtd_prorrogacao', models.BigIntegerField(default=1, editable=False)),
                ('diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diretoria', to='administrativo.diretoria', verbose_name='diretoria')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.usuario_petros')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.situacao')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_documento', to='core.tipo_documento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto')),
                ('documento_ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_ponto', to='demanda.documento', verbose_name='documento_ponto')),
            ],
            options={
                'verbose_name': 'Ponto',
                'verbose_name_plural': 'Pontos',
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recomendação')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto', to='demanda.ponto', verbose_name='ponto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customusuario', to='administrativo.usuario_petros', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
            },
        ),
        migrations.CreateModel(
            name='Historico_Documento',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Histórico')),
                ('dat_incl', models.DateTimeField(auto_now_add=True, verbose_name='Inclusão')),
                ('documento_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_hist', to='demanda.documento', verbose_name='documento_hist')),
            ],
            options={
                'verbose_name': 'Historico de Documento',
                'verbose_name_plural': 'Historicos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Csp',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_csp', models.CharField(blank=True, max_length=9, null=True, verbose_name='Número do CSP')),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição do CSP')),
                ('dat_registro', models.DateField(blank=True, null=True, verbose_name='Data de Registro')),
                ('dat_fim', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('dat_priorizacao', models.DateField(blank=True, null=True, verbose_name='Data de Priorização')),
                ('dat_prevista', models.DateField(blank=True, null=True, verbose_name='Previsão')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demanda.documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'CSP',
                'verbose_name_plural': 'CSPs',
            },
        ),
    ]
