# Generated by Django 3.2.6 on 2021-09-11 04:42

import administrativo.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('id_petros', models.CharField(max_length=7, verbose_name='id_petros')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Membro da equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', administrativo.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato da Demanda')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail Contato')),
                ('celular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Diretoria')),
                ('sigla', models.CharField(max_length=6, verbose_name='Sigla Diretoria')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Diretoria',
                'verbose_name_plural': 'Diretorias',
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Entidade')),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Breve descição')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Gerência')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla da Gerência')),
                ('email', models.EmailField(max_length=254)),
                ('diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.diretoria')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.entidade')),
            ],
            options={
                'verbose_name': 'Gerência',
                'verbose_name_plural': 'Gerências',
            },
        ),
        migrations.CreateModel(
            name='Origem_Documento',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Origem do Documento')),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Origem do Controle',
                'verbose_name_plural': 'Origems dos Controles',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla da Setor')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Setor')),
                ('email', models.EmailField(max_length=254)),
                ('diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.diretoria')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.entidade')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.gerencia')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'situação',
                'verbose_name_plural': 'situações',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Petros',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id_usu_petros', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usu', models.CharField(max_length=255, verbose_name='Nome')),
                ('diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.diretoria')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.entidade')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.gerencia')),
                ('setor_petros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.setor')),
                ('user_sistem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Petros',
                'verbose_name_plural': 'Usuarios Petros',
            },
        ),
        migrations.CreateModel(
            name='Nivel_Prorrogacao',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Prorrogação')),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nivel de Prorrogação')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autorizador Responsável')),
            ],
            options={
                'verbose_name': 'Nivél de Prorrogação',
                'verbose_name_plural': 'Niveis de Prorrogação',
            },
        ),
        migrations.AddField(
            model_name='diretoria',
            name='entidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.entidade'),
        ),
    ]
